site_name: pgdb | The postgres db handler you have dreamed of :)
repo_url: https://github.com/holdfenytolvaj/pogi
site_url: http://pogi.readthedocs.io
theme: readthedocs
pages:
- Home : index.md
- Connection : connection.md
- Executing SQL files : executingSqlFile.md
- Functions : functions.md
- Generate interface for Db : generatingInterfaceForTables.md
- Logger : logger.md
- Mapping database types : mappingDatabaseTypes.md
- Transaction : transaction.md
- Stream : streams.md
- FAQ : faq.md
- Known pitfalls : pitfalls.md
- API :
  - PgDb: API/PgDb.md
  - PgSchema: API/PgSchema.md
  - PgTable: API/PgTable.md
  - Condition : API/condition.md
  - Query options : API/QueryOptions.md
extra_css:
- css/docs.css
